sudo: false
language: node_js
node_js:
  - 4
  - 5
  - "stable"

before_install:
  - "npm config set progress=false"

before_script:
  - npm run lint

script: npm run cover

after_script:
  - "cat ./tests/coverage/final/lcov.info | ./node_modules/.bin/coveralls"
